version: "3.3"
services:
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "./db/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # logging:
    #   driver: none
  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    environment:
      ME_CONFIG_SITE_BASEURL: /admin/
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    # logging:
    #   driver: none
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    volumes:
      - ./openApi.json:/usr/share/nginx/html/doc/openApi.json
    environment:
      API_URL: doc/openApi.json
    logging:
      driver: none
  nginx:
    image: "nginx:alpine"
    container_name: mock-api-frontproxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/root/certs:/etc/nginx/certs"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    links:
      - api
      - mongo-express
      - swagger-ui
    logging:
      driver: none
  api:
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/hrlab-timetracking?authSource=admin
    build: .
    container_name: hrlab-timetracking-mock-api
    links:
      - mongo
    volumes:
      - ".:/app"
    restart: always
    command: "npm start"
    # logging:
    #   driver: none
