version: "3.3"
services:
  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - "./db/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    logging:
      driver: none
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8080:8080"
    volumes:
      - ./openApi.json:/usr/share/nginx/html/doc/openApi.json
    environment:
      API_URL: doc/openApi.json
  api:
    environment:
      DB_HOST: mongodb://root:root@mongo:27017/hrlab-timetracking?authSource=admin
    build: .
    container_name: hrlab-timetracking-mock-api
    depends_on:
      - mongo
    volumes:
      - ".:/app"
    ports:
      - "5000:3000"
    restart: always
    # logging:
    #   driver: none
